#%RAML 1.0
title: Azure ML Commitment Plans Management Client
version: 2016-05-01-preview
baseUri: management.azure.com
description: These APIs allow end users to operate on Azure Machine Learning Commitment Plans resources and their child Commitment Association resources. They support CRUD operations for commitment plans, get and list operations for commitment associations, moving commitment associations between commitment plans, and retrieving commitment plan usage history.
mediaType:
- application/json
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
types:
  CommitmentAssociation:
    type: Resource
    description: Represents the association between a commitment plan and some other resource, such as a Machine Learning web service.
  CommitmentAssociationListResult:
    type: object
    properties:
      nextLink?:
        type: string
        description: A URI to retrieve the next page of results.
      value?:
        type: array
        description: The set of results for this page.
        items:
          type: CommitmentAssociation
    description: A page of commitment association resources.
  CommitmentAssociationProperties:
    type: object
    properties:
      associatedResourceId?:
        type: string
        description: The ID of the resource this association points to, such as the ARM ID of an Azure ML web service.
      commitmentPlanId?:
        type: string
        description: The ARM ID of the parent Azure ML commitment plan.
      creationDate?:
        type: datetime
        description: The date at which this commitment association was created, in ISO 8601 format.
    description: Properties of an Azure ML commitment association.
  CommitmentPlan:
    type: Resource
    description: An Azure ML commitment plan resource.
  CommitmentPlanListResult:
    type: object
    properties:
      nextLink?:
        type: string
        description: A URI to retrieve the next page of results.
      value?:
        type: array
        description: The set of results for this page.
        items:
          type: CommitmentPlan
    description: A page of commitment plan resources.
  CommitmentPlanPatchPayload:
    type: object
    properties:
      tags?:
        type: Tags
        description: User-defined tags for the commitment plan.
      sku?:
        type: ResourceSku
        description: The commitment plan SKU.
    description: The payload to patch the Azure ML commitment plan with. Only tags and SKU may be modified on an existing commitment plan.
  CommitmentPlanProperties:
    type: object
    properties:
      chargeForOverage?:
        type: boolean
        description: Indicates whether usage beyond the commitment plan's included quantities will be charged.
      chargeForPlan?:
        type: boolean
        description: Indicates whether the commitment plan will incur a charge.
      creationDate?:
        type: datetime
        description: The date at which this commitment plan was created, in ISO 8601 format.
      includedQuantities?:
        type: object
        properties:
          //:
            type: PlanQuantity
        description: The included resource quantities this plan gives you.
      maxAssociationLimit?:
        type: integer
        description: The maximum number of commitment associations that can be children of this commitment plan.
        format: int32
      maxCapacityLimit?:
        type: integer
        description: The maximum scale-out capacity for this commitment plan.
        format: int32
      minCapacityLimit?:
        type: integer
        description: The minimum scale-out capacity for this commitment plan.
        format: int32
      planMeter?:
        type: string
        description: The Azure meter which will be used to charge for this commitment plan.
      refillFrequencyInDays?:
        type: integer
        description: The frequency at which this commitment plan's included quantities are refilled.
        format: int32
      suspendPlanOnOverage?:
        type: boolean
        description: Indicates whether this commitment plan will be moved into a suspended state if usage beyond the commitment plan's included quantities is incurred.
    description: Properties of an Azure ML commitment plan.
  MoveCommitmentAssociationRequest:
    type: object
    properties:
      destinationPlanId?:
        type: string
        description: The ARM ID of the commitment plan to re-parent the commitment association to.
    description: The move request payload.
  PlanQuantity:
    type: object
    properties:
      allowance?:
        type: number
        description: The quantity added to the commitment plan at an interval specified by its allowance frequency.
        format: double
      amount?:
        type: number
        description: The quantity available to the plan the last time usage was calculated.
        format: double
      includedQuantityMeter?:
        type: string
        description: The Azure meter for usage against included quantities.
      overageMeter?:
        type: string
        description: The Azure meter for usage which exceeds included quantities.
    description: Represents the quantity a commitment plan provides of a metered resource.
  PlanUsageHistory:
    type: object
    properties:
      planDeletionOverage?:
        type: object
        properties:
          //:
            type: number
            format: double
        description: Overage incurred as a result of deleting a commitment plan.
      planMigrationOverage?:
        type: object
        properties:
          //:
            type: number
            format: double
        description: Overage incurred as a result of migrating a commitment plan from one SKU to another.
      planQuantitiesAfterUsage?:
        type: object
        properties:
          //:
            type: number
            format: double
        description: Included quantities remaining after usage against the commitment plan's associated resources was calculated.
      planQuantitiesBeforeUsage?:
        type: object
        properties:
          //:
            type: number
            format: double
        description: Included quantities remaining before usage against the commitment plan's associated resources was calculated.
      planUsageOverage?:
        type: object
        properties:
          //:
            type: number
            format: double
        description: Usage against the commitment plan's associated resources which was not covered by included quantities and is therefore overage.
      usage?:
        type: object
        properties:
          //:
            type: number
            format: double
        description: Usage against the commitment plan's associated resources.
      usageDate?:
        type: datetime
        description: The date of usage, in ISO 8601 format.
    description: Represents historical information about usage of the Azure resources associated with a commitment plan.
  PlanUsageHistoryListResult:
    type: object
    properties:
      nextLink?:
        type: string
        description: A URI to retrieve the next page of results.
      value?:
        type: array
        description: The set of results for this page.
        items:
          type: PlanUsageHistory
    description: A page of usage history.
  Resource:
    type: object
    properties:
      id?:
        type: string
        description: Resource Id.
      name?:
        type: string
        description: Resource name.
      location:
        type: string
        description: Resource location.
      type?:
        type: string
        description: Resource type.
      tags?:
        type: Tags
        description: User-defined tags for the resource.
    description: Common properties of an ARM resource.
  ResourceSku:
    type: object
    properties:
      capacity?:
        type: integer
        description: The scale-out capacity of the resource. 1 is 1x, 2 is 2x, etc. This impacts the quantities and cost of any commitment plan resource.
        format: int32
      name?:
        type: string
        description: The SKU name. Along with tier, uniquely identifies the SKU.
      tier?:
        type: string
        description: The SKU tier. Along with name, uniquely identifies the SKU.
    description: The SKU of a resource.
  Tags:
    type: object
    properties:
      //:
        type: string
    description: Resource tags
/subscriptions:
  /{subscriptionId}:
    uriParameters:
      subscriptionId:
        type: string
        description: Azure Subscription ID.
        displayName: subscriptionId
    /providers:
      /Microsoft.MachineLearning:
        /commitmentPlans:
          get:
            description: Retrieve all Azure ML commitment plans in a subscription.
            queryParameters:
              $skipToken?:
                type: string
                description: Continuation token for pagination.
                displayName: $skipToken
              api-version:
                type: string
                description: The version of the Microsoft.MachineLearning resource provider API to use.
                displayName: api-version
            responses:
              200:
                description: OK
                body:
                  application/json:
                    type: CommitmentPlanListResult
    /resourceGroups:
      /{resourceGroupName}:
        uriParameters:
          resourceGroupName:
            type: string
            description: The resource group name.
            displayName: resourceGroupName
        /providers:
          /Microsoft.MachineLearning:
            /commitmentPlans:
              /{commitmentPlanName}:
                uriParameters:
                  commitmentPlanName:
                    type: string
                    description: The Azure ML commitment plan name.
                    displayName: commitmentPlanName
                /commitmentAssociations:
                  /{commitmentAssociationName}:
                    uriParameters:
                      commitmentAssociationName:
                        type: string
                        description: The commitment association name.
                        displayName: commitmentAssociationName
                    /move:
                      post:
                        description: Re-parents a commitment association from one commitment plan to another.
                        queryParameters:
                          api-version:
                            type: string
                            description: The version of the Microsoft.MachineLearning resource provider API to use.
                            displayName: api-version
                        body:
                          application/json: MoveCommitmentAssociationRequest
                        responses:
                          200:
                            description: OK
                            body:
                              application/json:
                                type: CommitmentAssociation
                    get:
                      description: Gets a commitment association.
                      queryParameters:
                        api-version:
                          type: string
                          description: The version of the Microsoft.MachineLearning resource provider API to use.
                          displayName: api-version
                      responses:
                        200:
                          description: OK
                          body:
                            application/json:
                              type: CommitmentAssociation
                  get:
                    description: Get all commitment associations for a parent commitment plan.
                    queryParameters:
                      $skipToken?:
                        type: string
                        description: Continuation token for pagination.
                        displayName: $skipToken
                      api-version:
                        type: string
                        description: The version of the Microsoft.MachineLearning resource provider API to use.
                        displayName: api-version
                    responses:
                      200:
                        description: OK
                        body:
                          application/json:
                            type: CommitmentAssociationListResult
                /usageHistory:
                  get:
                    description: Retrieves the usage history for an Azure ML commitment plan.
                    queryParameters:
                      $skipToken?:
                        type: string
                        description: Continuation token for pagination.
                        displayName: $skipToken
                      api-version:
                        type: string
                        description: The version of the Microsoft.MachineLearning resource provider API to use.
                        displayName: api-version
                    responses:
                      200:
                        description: OK
                        body:
                          application/json:
                            type: PlanUsageHistoryListResult
                get:
                  description: Retrieve an Azure ML commitment plan by its subscription, resource group and name.
                  queryParameters:
                    api-version:
                      type: string
                      description: The version of the Microsoft.MachineLearning resource provider API to use.
                      displayName: api-version
                  responses:
                    200:
                      description: OK
                      body:
                        application/json:
                          type: CommitmentPlan
                delete:
                  description: Remove an existing Azure ML commitment plan.
                  queryParameters:
                    api-version:
                      type: string
                      description: The version of the Microsoft.MachineLearning resource provider API to use.
                      displayName: api-version
                  responses:
                    200:
                      description: OK
                patch:
                  description: Patch an existing Azure ML commitment plan resource.
                  queryParameters:
                    api-version:
                      type: string
                      description: The version of the Microsoft.MachineLearning resource provider API to use.
                      displayName: api-version
                  body:
                    application/json: CommitmentPlanPatchPayload
                  responses:
                    200:
                      description: OK
                      body:
                        application/json:
                          type: CommitmentPlan
                put:
                  description: Creates a new Azure ML commitment plan resource or updates an existing one.
                  queryParameters:
                    api-version:
                      type: string
                      description: The version of the Microsoft.MachineLearning resource provider API to use.
                      displayName: api-version
                  body:
                    application/json: CommitmentPlan
                  responses:
                    200:
                      description: OK
                      body:
                        application/json:
                          type: CommitmentPlan
                    201:
                      description: Created
                      body:
                        application/json:
                          type: CommitmentPlan
              get:
                description: Retrieve all Azure ML commitment plans in a resource group.
                queryParameters:
                  $skipToken?:
                    type: string
                    description: Continuation token for pagination.
                    displayName: $skipToken
                  api-version:
                    type: string
                    description: The version of the Microsoft.MachineLearning resource provider API to use.
                    displayName: api-version
                responses:
                  200:
                    description: OK
                    body:
                      application/json:
                        type: CommitmentPlanListResult
