#%RAML 1.0
title: CognitiveServicesManagementClient
version: 2016-02-01-preview
baseUri: management.azure.com
description: Cognitive Services Management Client
mediaType:
- application/json
- text/json
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
types:
  CognitiveServicesAccount:
    type: object
    properties:
      etag?:
        type: string
        description: Entity Tag
      id?:
        type: string
        description: The id of the created account
      kind?:
        type: string
        description: Type of cognitive service account.
      location?:
        type: string
        description: The location of the resource
      name?:
        type: string
        description: The name of the created account
      properties?:
        type: CognitiveServicesAccountProperties
      sku?:
        type: Sku
      tags?:
        type: object
        properties:
          //:
            type: string
        description: Gets or sets a list of key value pairs that describe the resource. These tags can be used in viewing and grouping this resource (across resource groups). A maximum of 15 tags can be provided for a resource. Each tag must have a key no greater than 128 characters and value no greater than 256 characters.
      type?:
        type: string
        description: Resource type
    description: Cognitive Services Account is an Azure resource representing the provisioned account, its type, location and SKU.
  CognitiveServicesAccountCreateParameters:
    type: object
    properties:
      sku:
        type: Sku
      kind:
        type: string
        description: Required. Indicates the type of cognitive service account.
        enum:
        - ComputerVision
        - Emotion
        - Face
        - LUIS
        - Recommendations
        - Speech
        - TextAnalytics
        - WebLM
      location:
        type: string
        description: Required. Gets or sets the location of the resource. This will be one of the supported and registered Azure Geo Regions (e.g. West US, East US, Southeast Asia, etc.). The geo region of a resource cannot be changed once it is created, but if an identical geo region is specified on update the request will succeed.
      tags?:
        type: object
        properties:
          //:
            type: string
        description: Gets or sets a list of key value pairs that describe the resource. These tags can be used in viewing and grouping this resource (across resource groups). A maximum of 15 tags can be provided for a resource. Each tag must have a key no greater than 128 characters and value no greater than 256 characters.
      properties:
        type: CognitiveServicesAccountPropertiesCreateParameters
        description: Must exist in the request. Must not be null.
    description: The parameters to provide for the created account.
  CognitiveServicesAccountEnumerateSkusResult:
    type: object
    properties:
      value?:
        type: array
        description: Gets the list of Cognitive Services accounts and their properties.
        items:
          type: CognitiveServicesResourceAndSku
    description: The list of cognitive services accounts operation response.
  CognitiveServicesAccountKeys:
    type: object
    properties:
      key1?:
        type: string
        description: Gets the value of key 1.
      key2?:
        type: string
        description: Gets the value of key 2.
    description: The access keys for the cognitive services account.
  CognitiveServicesAccountListResult:
    type: object
    properties:
      value?:
        type: array
        description: Gets the list of Cognitive Services accounts and their properties.
        items:
          type: CognitiveServicesAccount
    description: The list of cognitive services accounts operation response.
  CognitiveServicesAccountProperties:
    type: object
    properties:
      provisioningState?:
        type: string
        description: Gets the status of the cognitive services account at the time the operation was called.
        enum:
        - Creating
        - ResolvingDNS
        - Succeeded
        - Failed
      endpoint?:
        type: string
        description: Endpoint of the created account
  CognitiveServicesAccountPropertiesCreateParameters:
    type: object
    description: required empty proprties object. Must be an empty object, and must exist in the request.
  CognitiveServicesAccountUpdateParameters:
    type: object
    properties:
      sku?:
        type: Sku
      tags?:
        type: object
        properties:
          //:
            type: string
        description: Gets or sets a list of key value pairs that describe the resource. These tags can be used in viewing and grouping this resource (across resource groups). A maximum of 15 tags can be provided for a resource. Each tag must have a key no greater than 128 characters and value no greater than 256 characters.
    description: The parameters to provide for the created account.
  CognitiveServicesResourceAndSku:
    type: object
    properties:
      resourceType?:
        type: string
        description: Resource Namespace and Type
      sku?:
        type: Sku
  Error:
    type: object
    properties:
      error?:
        type: ErrorBody
  ErrorBody:
    type: object
    properties:
      code:
        type: string
        description: error code
      message:
        type: string
        description: error message
  RegenerateKeyParameters:
    type: object
    properties:
      keyName?:
        type: string
        description: key name to generate (Key1|Key2)
        enum:
        - Key1
        - Key2
    description: regenerate key parameters.
  Sku:
    type: object
    properties:
      name:
        type: string
        description: Gets or sets the sku name. Required for account creation, optional for update.
        enum:
        - F0
        - S0
        - S1
        - S2
        - S3
        - S4
      tier?:
        type: string
        description: Gets the sku tier. This is based on the SKU name.
        enum:
        - Free
        - Standard
        - Premium
    description: The SKU of the cognitive services account.
/subscriptions:
  /{subscriptionId}:
    uriParameters:
      subscriptionId:
        type: string
        description: Azure Subscription ID.
        displayName: subscriptionId
    /providers:
      /Microsoft.CognitiveServices:
        /accounts:
          get:
            description: Returns all the resources of a particular type belonging to a subscription.
            queryParameters:
              api-version:
                type: string
                description: Version of the API to be used with the client request. Current version is 2016-02-01-preview
                displayName: api-version
            responses:
              200:
                description: "The resource provider should return 200 (OK) to indicate\
                  \ that the operation completed successfully. For other errors (e.g.\
                  \ internal errors) use the appropriate HTTP error code.\nThe nextLink\
                  \ field is expected to point to the URL the client should use to\
                  \ fetch the next page (per server side paging). This matches the\
                  \ OData guidelines for paged responses. If a resource provider does\
                  \ not support paging, it should return the same body but leave nextLink\
                  \ empty for future compatibility.\nFor a detailed explanation of\
                  \ each field in the response body, please refer to the request body\
                  \ description in the PUT resource section. "
                body:
                  application/json:
                    type: CognitiveServicesAccountListResult
                  text/json:
                    type: CognitiveServicesAccountListResult
              500:
                description: Error response describing why the operation failed
                body:
                  application/json:
                    type: Error
                  text/json:
                    type: Error
    /resourceGroups:
      /{resourceGroupName}:
        uriParameters:
          resourceGroupName:
            type: string
            description: The name of the resource group within the user's subscription.
            displayName: resourceGroupName
        /providers:
          /Microsoft.CognitiveServices:
            /accounts:
              /{accountName}:
                uriParameters:
                  accountName:
                    type: string
                    description: The name of the cognitive services account within the specified resource group. Cognitive Services account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
                    displayName: accountName
                    maxLength: 24
                    minLength: 3
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$
                /listKeys:
                  post:
                    description: Lists the account keys for the specified Cognitive Services account.
                    queryParameters:
                      api-version:
                        type: string
                        description: Version of the API to be used with the client request. Current version is 2016-02-01-preview
                        displayName: api-version
                    responses:
                      200:
                        description: |-
                          Returns with a response body containing the subscription keys for the resource: key1
                          The first API key for authentication when client calls the API endpoint.

                          key2
                          The second API key for authentication when client calls the API endpoint.
                        body:
                          application/json:
                            type: CognitiveServicesAccountKeys
                          text/json:
                            type: CognitiveServicesAccountKeys
                      500:
                        description: Error response describing why the operation failed
                        body:
                          application/json:
                            type: Error
                          text/json:
                            type: Error
                /regenerateKey:
                  post:
                    description: Regenerates the specified account key for the specified Cognitive Services account.
                    queryParameters:
                      api-version:
                        type: string
                        description: Version of the API to be used with the client request. Current version is 2016-02-01-preview
                        displayName: api-version
                    body:
                      application/json: RegenerateKeyParameters
                      text/json: RegenerateKeyParameters
                    responses:
                      200:
                        description: ''
                        body:
                          application/json:
                            type: CognitiveServicesAccountKeys
                          text/json:
                            type: CognitiveServicesAccountKeys
                      500:
                        description: Error response describing why the operation failed
                        body:
                          application/json:
                            type: Error
                          text/json:
                            type: Error
                /skus:
                  get:
                    description: List available SKUs for the requested Cognitive Services account
                    queryParameters:
                      api-version:
                        type: string
                        description: Version of the API to be used with the client request. Current version is 2016-02-01-preview
                        displayName: api-version
                    responses:
                      200:
                        description: "The resource provider should return 200 (OK)\
                          \ to indicate that the operation completed successfully.\n\
                          For a detailed explanation of each field in the response\
                          \ body, please refer to the request body description in\
                          \ the PUT resource section. The only GET specific properties\
                          \ are “name,” “type” and “id.”\nField\tDescription\nsku\t\
                          Required, object\n\tThe exact set of keys that define this\
                          \ sku. This matches the fields on the respective resource.\n\
                          sku.name\tRequired, string\n\tThe name of the SKU. This\
                          \ is typically a letter + number code, such as A0 or P3\n\
                          sku.tier\tRequired, string\n\tThe tier of this particular\
                          \ SKU. Typically one of:\n\t· Free\n\t· Basic\n\t· Standard\n\
                          \t· Premium\n"
                        body:
                          application/json:
                            type: CognitiveServicesAccountEnumerateSkusResult
                          text/json:
                            type: CognitiveServicesAccountEnumerateSkusResult
                      500:
                        description: Error response describing why the operation failed. If the resource does not exist, 404 (NotFound) will be returned.
                        body:
                          application/json:
                            type: Error
                          text/json:
                            type: Error
                get:
                  description: Returns a Cognitive Services account specified by the parameters.
                  queryParameters:
                    api-version:
                      type: string
                      description: Version of the API to be used with the client request. Current version is 2016-02-01-preview
                      displayName: api-version
                  responses:
                    200:
                      description: "The resource provider should return 200 (OK) to\
                        \ indicate that the operation completed successfully.\nFor\
                        \ a detailed explanation of each field in the response body,\
                        \ please refer to the request body description in the PUT\
                        \ resource section. The only GET specific properties are “\
                        name,” “type” and “id.”\nField\tDescription\nKind\trequired.\
                        \  String.\n\tThe API set for this API account. It can be\
                        \ \n\t· a single API, for example: Face API, Vision API, Speech\
                        \ API. \n\ta bundle of APIs:  Face + Speech, Vision + Emotion,\
                        \ etc.\nsku.name\tRequired.\n\tThe pricing tier/plan of this\
                        \ API. Could be: \n\tF0 - Free\n\tB0 - Basic\n\tS0 - Standard\n\
                        \tP0 - Premium\n"
                      body:
                        application/json:
                          type: CognitiveServicesAccount
                        text/json:
                          type: CognitiveServicesAccount
                    500:
                      description: Error response describing why the operation failed. If the resource does not exist, 404 (NotFound) should be returned.
                      body:
                        application/json:
                          type: Error
                        text/json:
                          type: Error
                delete:
                  description: 'Deletes a Cognitive Services account from the resource
                    group. '
                  queryParameters:
                    api-version:
                      type: string
                      description: Version of the API to be used with the client request. Current version is 2016-02-01-preview
                      displayName: api-version
                  responses:
                    200:
                      description: A 200 (OK) should be returned if the object exists and was deleted successfully;
                    204:
                      description: a 204 (NoContent) should be used if the resource does not exist and the request is well formed.
                    500:
                      description: Error response describing why the operation failed
                      body:
                        application/json:
                          type: Error
                        text/json:
                          type: Error
                patch:
                  description: Updates a Cognitive Services account
                  queryParameters:
                    api-version:
                      type: string
                      description: Version of the API to be used with the client request. Current version is 2016-02-01-preview
                      displayName: api-version
                  body:
                    application/json: CognitiveServicesAccountUpdateParameters
                    text/json: CognitiveServicesAccountUpdateParameters
                  responses:
                    200:
                      description: 'The resource provider should return 200 (OK) to
                        indicate that the operation completed successfully. '
                      body:
                        application/json:
                          type: CognitiveServicesAccount
                        text/json:
                          type: CognitiveServicesAccount
                    500:
                      description: Error response describing why the operation failed. If the resource group *or* resource does not exist, 404 (NotFound) should be returned.
                      body:
                        application/json:
                          type: Error
                        text/json:
                          type: Error
                put:
                  description: Create Cognitive Services Account. Accounts is a resource group wide resource type. It holds the keys for developer to access intelligent APIs. It's also the resource type for billing.
                  queryParameters:
                    api-version:
                      type: string
                      description: Version of the API to be used with the client request. Current version is 2016-02-01-preview
                      displayName: api-version
                  body:
                    application/json: CognitiveServicesAccountCreateParameters
                    text/json: CognitiveServicesAccountCreateParameters
                  responses:
                    200:
                      description: If resource is created successfully or already existed, the service should return 200 (OK).
                      body:
                        application/json:
                          type: CognitiveServicesAccount
                        text/json:
                          type: CognitiveServicesAccount
                    201:
                      description: If resource is created successfully, the service should return 201 (OK).
                      body:
                        application/json:
                          type: CognitiveServicesAccount
                        text/json:
                          type: CognitiveServicesAccount
                    500:
                      description: Error response describing why the operation failed
                      body:
                        application/json:
                          type: Error
                        text/json:
                          type: Error
              get:
                description: Returns all the resources of a particular type belonging to a resource group
                queryParameters:
                  api-version:
                    type: string
                    description: Version of the API to be used with the client request. Current version is 2016-02-01-preview
                    displayName: api-version
                responses:
                  200:
                    description: "The resource provider should return 200 (OK) to\
                      \ indicate that the operation completed successfully. For other\
                      \ errors (e.g. internal errors) use the appropriate HTTP error\
                      \ code.\nThe nextLink field is expected to point to the URL\
                      \ the client should use to fetch the next page (per server side\
                      \ paging). This matches the OData guidelines for paged responses\
                      \ here. If a resource provider does not support paging, it should\
                      \ return the same body (JSON object with “value” property) but\
                      \ omit nextLink entirely (or set to null, *not* empty string)\
                      \ for future compatibility.\nThe nextLink should be implemented\
                      \ using following query parameters:\n· skipToken: opaque token\
                      \ that allows the resource provider to skip resources already\
                      \ enumerated. This value is defined and returned by the RP after\
                      \ first request via nextLink.\n· top: the optional client query\
                      \ parameter which defines the maximum number of records to be\
                      \ returned by the server.\nImplementation details:\n· NextLink\
                      \ may include all the query parameters (specifically OData $filter)\
                      \ used by the client in the first query. \n· Server may return\
                      \ less records than requested with nextLink. Returning zero\
                      \ records with NextLink is an acceptable response. \nClients\
                      \ must fetch records until the nextLink is not returned back\
                      \ / null. Clients should never rely on number of returned records\
                      \ to determinate if pagination is completed."
                    body:
                      application/json:
                        type: CognitiveServicesAccountListResult
                      text/json:
                        type: CognitiveServicesAccountListResult
                  500:
                    description: Error response describing why the operation failed. If the resource group does not exist, 404 (NotFound) will be returned.
                    body:
                      application/json:
                        type: Error
                      text/json:
                        type: Error
