#%RAML 1.0
title: DataLakeAnalyticsJobManagementClient
version: 2015-11-01-preview
description: Creates an Azure Data Lake Analytics job client.
mediaType:
- application/json
- text/json
- application/octet-stream
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
types:
  HiveJobProperties:
    type: JobProperties
  HiveJobStatementInfo:
    type: object
    properties:
      logLocation?:
        type: string
        description: Gets or sets the log location for this statement.
      resultPreviewLocation?:
        type: string
        description: Gets or sets the result preview location for this statement.
      resultLocation?:
        type: string
        description: Gets or sets the result location for this statement.
      errorMessage?:
        type: string
        description: Gets or sets the error message for this statement.
  JobDataPath:
    type: object
    properties:
      jobId?:
        type: commons.uuid
        description: Gets the id of the job this data is for.
        (extras.Readonly): true
      command?:
        type: string
        description: Gets the command that this job data relates to.
        (extras.Readonly): true
      paths?:
        type: array
        description: Gets the list of paths to all of the job data.
        items:
          type: string
    description: A Data Lake Analytics U-SQL job data path item.
  JobErrorDetails:
    type: object
    properties:
      description?:
        type: string
        description: Gets the error message description
        (extras.Readonly): true
      details?:
        type: string
        description: Gets the details of the error message.
        (extras.Readonly): true
      endOffset?:
        type: integer
        description: Gets the end offset in the job where the error was found.
        format: int32
        (extras.Readonly): true
      errorId?:
        type: string
        description: Gets the specific identifier for the type of error encountered in the job.
        (extras.Readonly): true
      filePath?:
        type: string
        description: Gets the path to any supplemental error files, if any.
        (extras.Readonly): true
      helpLink?:
        type: string
        description: Gets the link to MSDN or Azure help for this type of error, if any.
        (extras.Readonly): true
      internalDiagnostics?:
        type: string
        description: Gets the internal diagnostic stack trace if the user requesting the job error details has sufficient permissions it will be retrieved, otherwise it will be empty.
        (extras.Readonly): true
      lineNumber?:
        type: integer
        description: Gets the specific line number in the job where the error occured.
        format: int32
        (extras.Readonly): true
      message?:
        type: string
        description: Gets the user friendly error message for the failure.
        (extras.Readonly): true
      resolution?:
        type: string
        description: Gets the recommended resolution for the failure, if any.
        (extras.Readonly): true
      InnerError?:
        type: JobInnerError
        description: Gets the inner error of this specific job error message, if any.
      severity?:
        type: string
        description: Gets the severity level of the failure.
        enum:
        - Warning
        - Error
        (extras.Readonly): true
      source?:
        type: string
        description: Gets the ultimate source of the failure (usually either SYSTEM or USER).
        (extras.Readonly): true
      startOffset?:
        type: integer
        description: Gets the start offset in the job where the error was found
        format: int32
        (extras.Readonly): true
    description: The Data Lake Analytics job error details.
  JobInfoListResult:
    type: object
    properties:
      value?:
        type: array
        description: Gets the list of jobInfo items.
        items:
          type: JobInformation
      nextLink?:
        type: string
        description: Gets the link (url) to the next page of results.
        (extras.Readonly): true
      count?:
        type: integer
        description: Gets the total count of results that are available, but might not be returned in the current page.
        format: int64
        (extras.Readonly): true
    description: List of jobInfo items.
  JobInformation:
    type: object
    properties:
      jobId?:
        type: commons.uuid
        description: Gets or sets the job's unique identifier (a GUID).
      name:
        type: string
        description: Gets or sets the friendly name of the job.
      type:
        type: string
        description: Gets or sets the job type of the current job (Hive or USql).
        enum:
        - USql
        - Hive
      submitter?:
        type: string
        description: Gets or sets the user or account that submitted the job.
      errorMessage?:
        type: array
        description: Gets the error message details for the job, if the job failed.
        items:
          type: JobErrorDetails
      degreeOfParallelism?:
        type: integer
        description: Gets or sets the degree of parallelism used for this job. This must be greater than 0.
        format: int32
      priority?:
        type: integer
        description: Gets or sets the priority value for the current job. Lower numbers have a higher priority. By default, a job has a priority of 1000. This must be greater than 0.
        format: int32
      submitTime?:
        type: datetime
        description: Gets the time the job was submitted to the service.
        (extras.Readonly): true
      startTime?:
        type: datetime
        description: Gets the start time of the job.
        (extras.Readonly): true
      endTime?:
        type: datetime
        description: Gets the completion time of the job.
        (extras.Readonly): true
      state?:
        type: string
        description: Gets the job state. When the job is in the Ended state, refer to Result and ErrorMessage for details.
        enum:
        - Accepted
        - Compiling
        - Ended
        - New
        - Queued
        - Running
        - Scheduling
        - Starting
        - Paused
        - WaitingForCapacity
        (extras.Readonly): true
      result?:
        type: string
        description: Gets the result of job execution or the current result of the running job.
        enum:
        - None
        - Succeeded
        - Cancelled
        - Failed
        (extras.Readonly): true
      stateAuditRecords?:
        type: array
        description: Gets the job state audit records, indicating when various operations have been performed on this job.
        items:
          type: JobStateAuditRecord
      properties:
        type: JobProperties
        description: Gets or sets the job specific properties.
    description: The parameters to submit a job.
  JobInnerError:
    type: object
    properties:
      diagnosticCode?:
        type: integer
        description: Gets the diagnostic error code.
        format: int32
        (extras.Readonly): true
      severity?:
        type: string
        description: Gets the severity level of the failure.
        enum:
        - Warning
        - Error
        (extras.Readonly): true
      details?:
        type: string
        description: Gets the details of the error message.
        (extras.Readonly): true
      component?:
        type: string
        description: Gets the component that failed.
        (extras.Readonly): true
      errorId?:
        type: string
        description: Gets the specific identifier for the type of error encountered in the job.
        (extras.Readonly): true
      helpLink?:
        type: string
        description: Gets the link to MSDN or Azure help for this type of error, if any.
        (extras.Readonly): true
      internalDiagnostics?:
        type: string
        description: Gets the internal diagnostic stack trace if the user requesting the job error details has sufficient permissions it will be retrieved, otherwise it will be empty.
        (extras.Readonly): true
      message?:
        type: string
        description: Gets the user friendly error message for the failure.
        (extras.Readonly): true
      resolution?:
        type: string
        description: Gets the recommended resolution for the failure, if any.
        (extras.Readonly): true
      source?:
        type: string
        description: Gets the ultimate source of the failure (usually either SYSTEM or USER).
        (extras.Readonly): true
      description?:
        type: string
        description: Gets the error message description
        (extras.Readonly): true
    description: The Data Lake Analytics job error details.
  JobProperties:
    type: object
    properties:
      runtimeVersion?:
        type: string
        description: Gets or sets the runtime version of the U-SQL engine to use
      script:
        type: string
        description: Gets or sets the U-SQL script to run
      type:
        type: string
        description: Gets or sets the job type of the current job (i.e. Hive or U-SQL).
    description: The common Data Lake Analytics job properties.
    discriminator: type
  JobResource:
    type: object
    properties:
      name?:
        type: string
        description: Gets or set the name of the resource.
      resourcePath?:
        type: string
        description: Gets or sets the path to the resource.
      type?:
        type: string
        description: Gets or sets the job resource type.
        enum:
        - VertexResource
        - StatisticsResource
    description: The Data Lake Analytics U-SQL job resources.
  JobStateAuditRecord:
    type: object
    properties:
      newState?:
        type: string
        description: Gets the new state the job is in.
        (extras.Readonly): true
      timeStamp?:
        type: datetime
        description: Gets the time stamp that the state change took place.
        (extras.Readonly): true
      requestedByUser?:
        type: string
        description: Gets the user who requests the change.
        (extras.Readonly): true
      details?:
        type: string
        description: Gets  the details of the audit log.
        (extras.Readonly): true
    description: The Data Lake Analytics U-SQL job state audit records for tracking the lifecycle of a job.
  JobStatistics:
    type: object
    properties:
      lastUpdateTimeUtc?:
        type: datetime
        description: Gets the last update time for the statistics.
        (extras.Readonly): true
      stages?:
        type: array
        description: Gets the list of stages for the job.
        items:
          type: JobStatisticsVertexStage
    description: The Data Lake Analytics U-SQL job execution statistics.
  JobStatisticsVertexStage:
    type: object
    properties:
      dataRead?:
        type: integer
        description: Gets the amount of data read, in bytes.
        format: int64
        (extras.Readonly): true
      dataReadCrossPod?:
        type: integer
        description: Gets the amount of data read across multiple pods, in bytes.
        format: int64
        (extras.Readonly): true
      dataReadIntraPod?:
        type: integer
        description: Gets the amount of data read in one pod, in bytes.
        format: int64
        (extras.Readonly): true
      dataToRead?:
        type: integer
        description: Gets the amount of data remaining to be read, in bytes.
        format: int64
        (extras.Readonly): true
      dataWritten?:
        type: integer
        description: Gets the amount of data written, in bytes.
        format: int64
        (extras.Readonly): true
      duplicateDiscardCount?:
        type: integer
        description: Gets the number of duplicates that were discarded.
        format: int32
        (extras.Readonly): true
      failedCount?:
        type: integer
        description: Gets the number of failures that occured in this stage.
        format: int32
        (extras.Readonly): true
      maxVertexDataRead?:
        type: integer
        description: Gets the maximum amount of data read in a single vertex, in bytes.
        format: int64
        (extras.Readonly): true
      minVertexDataRead?:
        type: integer
        description: Gets the minimum amount of data read in a single vertex, in bytes.
        format: int64
        (extras.Readonly): true
      readFailureCount?:
        type: integer
        description: Gets the number of read failures in this stage.
        format: int32
        (extras.Readonly): true
      revocationCount?:
        type: integer
        description: Gets the number of vertices that were revoked during this stage.
        format: int32
        (extras.Readonly): true
      runningCount?:
        type: integer
        description: Gets the number of currently running vertices in this stage.
        format: int32
        (extras.Readonly): true
      scheduledCount?:
        type: integer
        description: Gets the number of currently scheduled vertices in this stage
        format: int32
        (extras.Readonly): true
      stageName?:
        type: string
        description: Gets the name of this stage in job execution.
        (extras.Readonly): true
      succeededCount?:
        type: integer
        description: Gets the number of vertices that succeeded in this stage.
        format: int32
        (extras.Readonly): true
      tempDataWritten?:
        type: integer
        description: Gets the amount of temporary data written, in bytes.
        format: int64
        (extras.Readonly): true
      totalCount?:
        type: integer
        description: Gets the total vertex count for this stage.
        format: int32
        (extras.Readonly): true
      totalFailedTime?:
        type: string
        description: Gets the amount of time that failed vertices took up in this stage.
        (extras.Readonly): true
      totalProgress?:
        type: integer
        description: Gets the current progress of this stage, as a percentage.
        format: int32
        (extras.Readonly): true
      totalSucceededTime?:
        type: string
        description: Gets the amount of time all successful vertices took in this stage.
        (extras.Readonly): true
    description: The Data Lake Analytics U-SQL job statistics vertex stage information.
  USqlJobProperties:
    type: JobProperties
/BuildJob:
  post:
    description: Builds (compiles) the specified job in the specified Data Lake Analytics account for job correctness and validation.
    queryParameters:
      api-version:
        type: string
        description: Client Api Version.
        displayName: api-version
    body:
      application/json: JobInformation
      text/json: JobInformation
      application/octet-stream: JobInformation
    responses:
      200:
        description: ''
        body:
          application/json:
            type: JobInformation
          text/json:
            type: JobInformation
          application/octet-stream:
            type: JobInformation
/Jobs:
  /{jobIdentity}:
    uriParameters:
      jobIdentity:
        type: commons.uuid
        description: JobInfo ID.
        displayName: jobIdentity
    /CancelJob:
      post:
        description: Cancels the running job specified by the job ID.
        queryParameters:
          api-version:
            type: string
            description: Client Api Version.
            displayName: api-version
        responses:
          200:
            description: ''
    /GetDebugDataPath:
      post:
        description: Gets the U-SQL job debug data information specified by the job ID.
        queryParameters:
          api-version:
            type: string
            description: Client Api Version.
            displayName: api-version
        responses:
          200:
            description: ''
            body:
              application/json:
                type: JobDataPath
              text/json:
                type: JobDataPath
              application/octet-stream:
                type: JobDataPath
    /GetStatistics:
      post:
        description: Gets statistics of the specified job.
        queryParameters:
          api-version:
            type: string
            description: Client Api Version.
            displayName: api-version
        responses:
          200:
            description: ''
            body:
              application/json:
                type: JobStatistics
              text/json:
                type: JobStatistics
              application/octet-stream:
                type: JobStatistics
    get:
      description: Gets the job information for the specified job ID.
      queryParameters:
        api-version:
          type: string
          description: Client Api Version.
          displayName: api-version
      responses:
        200:
          description: ''
          body:
            application/json:
              type: JobInformation
            text/json:
              type: JobInformation
            application/octet-stream:
              type: JobInformation
    put:
      description: Submits a job to the specified Data Lake Analytics account.
      queryParameters:
        api-version:
          type: string
          description: Client Api Version.
          displayName: api-version
      body:
        application/json: JobInformation
        text/json: JobInformation
        application/octet-stream: JobInformation
      responses:
        200:
          description: ''
          body:
            application/json:
              type: JobInformation
            text/json:
              type: JobInformation
            application/octet-stream:
              type: JobInformation
  get:
    description: Lists the jobs, if any, associated with the specified Data Lake Analytics account. The response includes a link to the next page of results, if any.
    queryParameters:
      $filter?:
        type: string
        description: OData filter. Optional.
        displayName: $filter
      $top?:
        type: integer
        description: The number of items to return. Optional.
        displayName: $top
        format: int32
      $skip?:
        type: integer
        description: The number of items to skip over before returning elements. Optional.
        displayName: $skip
        format: int32
      $expand?:
        type: string
        description: OData expansion. Expand related resources in line with the retrieved resources, e.g. Categories/$expand=Products would expand Product data in line with each Category entry. Optional.
        displayName: $expand
      $select?:
        type: string
        description: OData Select statement. Limits the properties on each entry to just those requested, e.g. Categories?$select=CategoryName,Description. Optional.
        displayName: $select
      $orderby?:
        type: string
        description: OrderBy clause. One or more comma-separated expressions with an optional "asc" (the default) or "desc" depending on the order you'd like the values sorted, e.g. Categories?$orderby=CategoryName desc. Optional.
        displayName: $orderby
      $count?:
        type: boolean
        description: The Boolean value of true or false to request a count of the matching resources included with the resources in the response, e.g. Categories?$count=true. Optional.
        displayName: $count
      $search?:
        type: string
        description: A free form search. A free-text search expression to match for whether a particular entry should be included in the feed, e.g. Categories?$search=blue OR green. Optional.
        displayName: $search
      $format?:
        type: string
        description: The return format. Return the response in particular formatxii without access to request headers for standard content-type negotiation (e.g Orders?$format=json). Optional.
        displayName: $format
      api-version:
        type: string
        description: Client Api Version.
        displayName: api-version
    responses:
      200:
        description: ''
        body:
          application/json:
            type: JobInfoListResult
          text/json:
            type: JobInfoListResult
          application/octet-stream:
            type: JobInfoListResult
    (extras.Pagination):
      nextLinkName: nextLink
