#%RAML 1.0
title: ManagementLockClient
version: '2016-09-01'
baseUri: management.azure.com
mediaType:
- application/json
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
securitySchemes:
  azure_auth:
    type: OAuth 2.0
    description: Azure Active Directory OAuth2 Flow
    settings:
      authorizationGrants:
      - implicit
      authorizationUri: https://login.microsoftonline.com/common/oauth2/authorize
      accessTokenUri: https://login.microsoftonline.com/common/oauth2/authorize
      scopes:
      - user_impersonation
types:
  ManagementLockListResult:
    type: object
    properties:
      value?:
        type: array
        description: The list of locks.
        items:
          type: ManagementLockObject
      nextLink?:
        type: string
        description: The URL to get the next set of results.
    description: The list of locks.
  ManagementLockObject:
    type: object
    properties:
      properties:
        type: ManagementLockProperties
        description: The properties of the lock.
      id?:
        type: string
        description: The Id of the lock.
      type?:
        type: string
        description: The type of the lock.
      name?:
        type: string
        description: The name of the lock.
    description: Create or update management lock parameters.
  ManagementLockOwner:
    type: object
    properties:
      applicationId?:
        type: string
        description: The application Id of the lock owner.
  ManagementLockProperties:
    type: object
    properties:
      level:
        type: string
        description: The lock level of the lock.
        enum:
        - NotSpecified
        - CanNotDelete
        - ReadOnly
      notes?:
        type: string
        description: The notes of the lock.
      owners?:
        type: array
        description: The owners of the lock.
        items:
          type: ManagementLockOwner
    description: The lock properties.
/subscriptions:
  /{subscriptionId}:
    uriParameters:
      subscriptionId:
        type: string
        description: Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
        displayName: subscriptionId
    /providers:
      /Microsoft.Authorization:
        /locks:
          /{lockName}:
            uriParameters:
              lockName:
                type: string
                description: Name of the management lock.
                displayName: lockName
            get:
              description: Gets the management lock of a scope.
              queryParameters:
                api-version:
                  type: string
                  description: Client Api Version.
                  displayName: api-version
              responses:
                200:
                  description: OK
                  body:
                    application/json:
                      type: ManagementLockObject
            delete:
              description: Deletes the management lock of a subscription.
              queryParameters:
                api-version:
                  type: string
                  description: Client Api Version.
                  displayName: api-version
              responses:
                200:
                  description: OK
                204:
                  description: NoContent
            put:
              description: Create or update a management lock at the subscription level.
              queryParameters:
                api-version:
                  type: string
                  description: Client Api Version.
                  displayName: api-version
              body:
                application/json: ManagementLockObject
              responses:
                200:
                  description: OK
                  body:
                    application/json:
                      type: ManagementLockObject
                201:
                  description: Created
                  body:
                    application/json:
                      type: ManagementLockObject
          get:
            description: Gets all the management locks of a subscription.
            queryParameters:
              $filter?:
                type: string
                description: The filter to apply on the operation.
                displayName: $filter
              api-version:
                type: string
                description: Client Api Version.
                displayName: api-version
            responses:
              200:
                description: OK
                body:
                  application/json:
                    type: ManagementLockListResult
            (extras.Pagination):
              nextLinkName: nextLink
    /resourceGroups:
      /{resourceGroupName}:
        uriParameters:
          resourceGroupName:
            type: string
            description: Resource group name.
            displayName: resourceGroupName
            maxLength: 90
            minLength: 1
            pattern: ^[-\w\._\(\)]+$
        /providers:
          /Microsoft.Authorization:
            /locks:
              /{lockName}:
                uriParameters:
                  lockName:
                    type: string
                    description: The lock name.
                    displayName: lockName
                get:
                  description: Gets a management lock at the resource group level.
                  queryParameters:
                    api-version:
                      type: string
                      description: Client Api Version.
                      displayName: api-version
                  responses:
                    200:
                      description: OK
                      body:
                        application/json:
                          type: ManagementLockObject
                delete:
                  description: Deletes the management lock of a resource group.
                  queryParameters:
                    api-version:
                      type: string
                      description: Client Api Version.
                      displayName: api-version
                  responses:
                    200:
                      description: OK
                    204:
                      description: NoContent
                put:
                  description: Create or update a management lock at the resource group level.
                  queryParameters:
                    api-version:
                      type: string
                      description: Client Api Version.
                      displayName: api-version
                  body:
                    application/json: ManagementLockObject
                  responses:
                    200:
                      description: OK
                      body:
                        application/json:
                          type: ManagementLockObject
                    201:
                      description: Created
                      body:
                        application/json:
                          type: ManagementLockObject
              get:
                description: Gets all the management locks of a resource group.
                queryParameters:
                  $filter?:
                    type: string
                    description: The filter to apply on the operation.
                    displayName: $filter
                  api-version:
                    type: string
                    description: Client Api Version.
                    displayName: api-version
                responses:
                  200:
                    description: OK
                    body:
                      application/json:
                        type: ManagementLockListResult
                (extras.Pagination):
                  nextLinkName: nextLink
    /resourcegroups:
      /{resourceGroupName}:
        uriParameters:
          resourceGroupName:
            type: string
            description: The name of the resource group. The name is case insensitive.
            displayName: resourceGroupName
            maxLength: 90
            minLength: 1
            pattern: ^[-\w\._\(\)]+$
        /providers:
          /{resourceProviderNamespace}:
            uriParameters:
              resourceProviderNamespace:
                type: string
                description: Resource identity.
                displayName: resourceProviderNamespace
            /{parentResourcePath}:
              uriParameters:
                parentResourcePath:
                  type: string
                  description: Resource identity.
                  displayName: parentResourcePath
              /{resourceType}:
                uriParameters:
                  resourceType:
                    type: string
                    description: Resource identity.
                    displayName: resourceType
                /{resourceName}:
                  uriParameters:
                    resourceName:
                      type: string
                      description: Resource identity.
                      displayName: resourceName
                  /providers:
                    /Microsoft.Authorization:
                      /locks:
                        /{lockName}:
                          uriParameters:
                            lockName:
                              type: string
                              description: The name of lock.
                              displayName: lockName
                          delete:
                            description: Deletes the management lock of a resource or any level below resource.
                            queryParameters:
                              api-version:
                                type: string
                                description: Client Api Version.
                                displayName: api-version
                            responses:
                              200:
                                description: OK
                              204:
                                description: NoContent
                          put:
                            description: Create or update a management lock at the resource level or any level below resource.
                            queryParameters:
                              api-version:
                                type: string
                                description: Client Api Version.
                                displayName: api-version
                            body:
                              application/json: ManagementLockObject
                            responses:
                              200:
                                description: OK
                                body:
                                  application/json:
                                    type: ManagementLockObject
                              201:
                                description: Created
                                body:
                                  application/json:
                                    type: ManagementLockObject
                        get:
                          description: Gets all the management locks of a resource or any level below resource.
                          queryParameters:
                            $filter?:
                              type: string
                              description: The filter to apply on the operation.
                              displayName: $filter
                            api-version:
                              type: string
                              description: Client Api Version.
                              displayName: api-version
                          responses:
                            200:
                              description: OK
                              body:
                                application/json:
                                  type: ManagementLockListResult
                          (extras.Pagination):
                            nextLinkName: nextLink
