#%RAML 1.0
title: SubscriptionClient
version: '2016-06-01'
baseUri: management.azure.com
mediaType:
- application/json
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
securitySchemes:
  azure_auth:
    type: OAuth 2.0
    description: Azure Active Directory OAuth2 Flow
    settings:
      authorizationGrants:
      - implicit
      authorizationUri: https://login.microsoftonline.com/common/oauth2/authorize
      accessTokenUri: https://login.microsoftonline.com/common/oauth2/authorize
      scopes:
      - user_impersonation
types:
  Location:
    type: object
    properties:
      id?:
        type: string
        description: The fully qualified Id of the location. For example, /subscriptions/00000000-0000-0000-0000-000000000000/locations/westus.
      subscriptionId?:
        type: string
        description: The subscription Id.
      name?:
        type: string
        description: The location name.
      displayName?:
        type: string
        description: The display name of the location.
      latitude?:
        type: string
        description: The latitude of the location.
      longitude?:
        type: string
        description: The longitude of the location.
    description: Location information.
  LocationListResult:
    type: object
    properties:
      value?:
        type: array
        description: The locations.
        items:
          type: Location
    description: Location list operation response.
  Subscription:
    type: object
    properties:
      id?:
        type: string
        description: The fully qualified Id. For example, /subscriptions/00000000-0000-0000-0000-000000000000.
      subscriptionId?:
        type: string
        description: The subscription Id.
      tenantId?:
        type: string
        description: The tenant Id.
      displayName?:
        type: string
        description: The subscription display name.
      state?:
        type: string
        description: The subscription state.
        enum:
        - Enabled
        - Warned
        - PastDue
        - Disabled
        - Deleted
      subscriptionPolicies?:
        type: SubscriptionPolicies
        description: The subscription policies.
      authorizationSource?:
        type: string
        description: The authorization source of the request. Valid values are one or more combinations of Legacy, RoleBased, Bypassed, Direct and Management. For example, 'Legacy, RoleBased'.
    description: Subscription information.
  SubscriptionListResult:
    type: object
    properties:
      value?:
        type: array
        description: The subscriptions.
        items:
          type: Subscription
      nextLink:
        type: string
        description: The URL to get the next set of results.
    description: Subscription list operation response.
  SubscriptionPolicies:
    type: object
    properties:
      locationPlacementId?:
        type: string
        description: The subscription location placement Id. The Id indicates which regions are visible for a subscription. For example, a subscription with a location placement Id of Public_2014-09-01 has access to Azure public regions.
      quotaId?:
        type: string
        description: The subscription quota Id.
      spendingLimit?:
        type: string
        description: The subscription spending limit.
        enum:
        - 'On'
        - 'Off'
        - CurrentPeriodOff
    description: Subscription policies.
  TenantIdDescription:
    type: object
    properties:
      id?:
        type: string
        description: The fully qualified Id. For example, /tenants/00000000-0000-0000-0000-000000000000.
      tenantId?:
        type: string
        description: The tenantId. For example, 00000000-0000-0000-0000-000000000000.
    description: Tenant Id information.
  TenantListResult:
    type: object
    properties:
      value?:
        type: array
        description: The tenant Ids.
        items:
          type: TenantIdDescription
      nextLink:
        type: string
        description: The URL to get the next set of results.
    description: Tenant Ids information.
/subscriptions:
  /{subscriptionId}:
    uriParameters:
      subscriptionId:
        type: string
        description: Id of the subscription.
        displayName: subscriptionId
    /locations:
      get:
        description: Gets a list of the subscription locations.
        queryParameters:
          api-version:
            type: string
            description: Client Api Version.
            displayName: api-version
    get:
      description: Gets details about particular subscription.
      queryParameters:
        api-version:
          type: string
          description: Client Api Version.
          displayName: api-version
  get:
    description: Gets a list of subscriptions.
    queryParameters:
      api-version:
        type: string
        description: Client Api Version.
        displayName: api-version
/tenants:
  get:
    description: Gets a list of tenants.
    queryParameters:
      api-version:
        type: string
        description: Client Api Version.
        displayName: api-version
